version: '3.8'

services:
   app:
     build: .
     depends_on:
      - mongo
     env_file:
      - .env
     ports:
      - "3000:3000"   
   mongo:
     image: mongo
     restart: always
     ports:
       - "27017:27017"
