name: Deploy to server via docker compose

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: copy files and run docker compose on server
        uses: appleboy/ssh-action@v0.1.7
        with:

          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            cd /sourabh/todo
            git pull origin main
            docker compose down
            docker compose up -d --build
