name: Deploy to server via docker compose

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Test SSH connection
        uses: appleboy/ssh-action@v0.1.7
        with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              echo "✅ SSH connection successful!"
              hostname
              uptime
              
      - name: copy files and run docker compose on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /sourabh/todo
            git pull origin main
            docker compose down
            docker compose up -d --build
            echo "⏳ Waiting for app to become reachable on port 3000..."
            for i in {1..20}; do
              nc -z localhost 3000 && echo "✅ App is up!" && break
              echo "⏱️ Waiting... ($i)"
              sleep 5
            done
