name: checking deployment connectoion
on:
 push:
  branches: [ main ]
jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:

    - name: Test SSH connection
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          echo "✅ SSH connection successful!"
          hostname
          uptime
